#!/bin/bash
# Source app helpers
source /usr/share/yunohost/helpers
source .fonctions
set -eu

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

script_dir=$PWD

# Vérifie que les variables ne sont pas vides.
CHECK_VAR "$app" "app name not set"
CHECK_VAR "$script_dir" "script_dir not set"

CHECK_PATH	# Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.

CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.

# Install dependency to convert tracks to a readable format for the browser
sudo cp -a ../conf/osmw.list /etc/apt/sources.list.d/
sudo apt-get update


# Install dependency to convert tracks to a readable format for the browser
sudo apt-get update
sudo apt-get -t stretch -y install ruby2.3 libruby2.3 ruby2.3-dev \
                     libmagickwand-dev libxml2-dev libxslt1-dev nodejs \
                     build-essential git-core \
                     postgresql postgresql-contrib libpq-dev postgresql-server-dev-all \
                     libsasl2-dev imagemagick
sudo gem2.3 install bundler

# Prepare Umap to be installed
sudo git clone https://github.com/openstreetmap/openstreetmap-website.git /srv/$app
pushd /srv/$app
sudo bundle install
popd


# Setting up the database
dbname=$app
dbuser=$app

# Generate random password
dbpass=$(ynh_string_random)
##### dbpass
ynh_psql_create_db "$dbname" "$dbuser" "$dbpass"


sed -i "s@DBNAME@$dbname@g" ../conf/database.yml
sed -i "s@DBUSER@$dbuser@g" ../conf/database.yml
sed -i "s@DBPASS@$dbpass@g" ../conf/database.yml
sed -i "s@SERVER_URL@https://$domain$path@g" ../conf/application.yml

sudo cp ./conf/application.yml /srv/${app}/config/application.yml
sudo cp ./conf/database.yml /srv/${app}/config/database.yml

sudo -u postgres -i
createuser -s <username>
exit

pushd /srv/$app
sudo bundle exec rake db:create
sudo psql -d openstreetmap -c "CREATE EXTENSION btree_gist"

cd db/functions
sudo make libpgosm.so
cd ../..

sudo psql -d openstreetmap -c "CREATE FUNCTION maptile_for_point(int8, int8, int4) RETURNS int4 AS '`pwd`/db/functions/libpgosm', 'maptile_for_point' LANGUAGE C STRICT"
sudo psql -d openstreetmap -c "CREATE FUNCTION tile_for_point(int4, int4) RETURNS int8 AS '`pwd`/db/functions/libpgosm', 'tile_for_point' LANGUAGE C STRICT"
sudo psql -d openstreetmap -c "CREATE FUNCTION xid_to_int4(xid) RETURNS int4 AS '`pwd`/db/functions/libpgosm', 'xid_to_int4' LANGUAGE C STRICT"

sudo bundle exec rake db:migrate
sudo bundle exec rake test:db

sudo yunohost firewall allow Both 3000
pre_inst_osmw

sudo service osmw enable
sudo service osmw start
 

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
nginxconf=/etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf

ynh_app_setting_set "$app" is_public "$is_public"
if [ "$is_public" = "Yes" ];
then
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

sudo service nginx reload
sudo yunohost app ssowatconf
